version: "3"
services:
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: planetfarms
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - 8081:8080
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: planetfarms@ole.org
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 8082:80
  nginx:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./api/files:/usr/share/nginx/html
  planetapi:
    image: earthowned/planetapi
    ports:
     - 5000:5000
    volumes:
    - ./api/.env:/.env
    - ./api/src/middleware/jwks.json:/src/middleware/jwks.json
    - ./api/files:/files
    depends_on:
      - db
  planetfarms:
    build: .
    image: planetfarms-tags:amd64
    volumes:
      - ./frontend.default.conf:/etc/nginx/conf.d/default.conf
    ports:
     - 3000:80    