version: "3"
services:
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: planetfarms
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - 8081:8080
  nginx:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./api/files:/usr/share/nginx/html
  proxy:
    image: nginx:alpine
    ports:
      - 8090:80
    volumes:
      - ./nginx.default.conf:/etc/nginx/conf.d/default.conf
  frontend:
    #build: .
    image: earthowned:farms
    ports:
      - 8091:80
    volumes:
      - ./frontend.default.conf:/etc/nginx/conf.d/default.conf
  api:
    #build: ./api
    image: earthowned/planet-api
    ports:
      - 8092:5000
    depends_on:
      - db
    volumes:
      - ./api/files:/files
