export const CALENDER_EVENT_LIST_REQUEST = 'CALENDER_EVENT_LIST_REQUEST'
export const CALENDER_EVENT_LIST_SUCCESS = 'CALENDER_EVENT_LIST_SUCCESS'
export const CALENDER_EVENT_LIST_FAIL = 'CALENDER_EVENT_LIST_FAIL'

export const CALENDER_EVENT_CREATE_REQUEST = 'CALENDER_EVENT_CREATE_REQUEST'
export const CALENDER_EVENT_CREATE_SUCCESS = 'CALENDER_EVENT_CREATE_SUCCESS'
export const CALENDER_EVENT_CREATE_FAIL = 'CALENDER_EVENT_CREATE_FAIL'

export const CALENDER_EVENT_LIST_BYID_REQUEST = 'CALENDER_EVENT_CREATE_LIST_BYID_REQUEST'
export const CALENDER_EVENT_LIST_BYID_SUCCESS = 'CALENDER_EVENT_LIST_BYID_SUCCESS'
export const CALENDER_EVENT_LIST_BYID_FAIL = 'CALENDER_EVENT_LIST_BYID_FAIL'
