export const COLLECTION_USER_LIST_REQUEST = 'COLLECTION_USER_LIST_REQUEST'
export const COLLECTION_USER_LIST_SUCCESS = 'COLLECTION_USER_LIST_SUCCESS'
export const COLLECTION_USER_LIST_FAIL = 'COLLECTION_USER_LIST_FAIL'

export const COLLECTION_USER_CREATE_REQUEST = 'COLLECTION_USER_CREATE_REQUEST'
export const COLLECTION_USER_CREATE_SUCCESS = 'COLLECTION_USER_CREATE_SUCCESS'
export const COLLECTION_USER_CREATE_FAIL = 'COLLECTION_USER_CREATE_FAIL'
