export const COMMUNITY_LIST_REQUEST = 'COMMUNITY_LIST_REQUEST'
export const COMMUNITY_LIST_SUCCESS = 'COMMUNITY_LIST_SUCCESS'
export const COMMUNITY_LIST_FAIL = 'COMMUNITY_LIST_FAIL'

export const COMMUNITY_SEARCH_REQUEST =  'COMMUNITY_SEARCH_REQUEST'
export const COMMUNITY_SEARCH_SUCCESS =  'COMMUNITY_SEARCH_SUCCESS'
export const COMMUNITY_SEARCH_FAIL =  'COMMUNITY_SEARCH_FAIL'

export const COMMUNITY_CREATE_REQUEST = 'COMMUNITY_CREATE_REQUEST'
export const COMMUNITY_CREATE_SUCCESS = 'COMMUNITY_CREATE_SUCCESS'
export const COMMUNITY_CREATE_FAIL = 'COMMUNITY_CREATE_FAIL'
export const COMMUNITY_CREATE_RESET = 'COMMUNITY_CREATE_RESET'

export const COMMUNITY_JOIN_REQUEST = 'COMMUNITY_JOIN_REQUEST'
export const COMMUNITY_JOIN_SUCCESS = 'COMMUNITY_JOIN_SUCCESS'
export const COMMUNITY_JOIN_FAIL = 'COMMUNITY_JOIN_FAIL'


export const GROUP_LIST_BYID_REQUEST = 'GROUP_LIST_BYID_REQUEST'
export const GROUP_LIST_BYID_SUCCESS = 'GROUP_LIST_BYID_SUCCESS'
export const GROUP_LIST_BYID_FAIL = 'GROUP_LIST_BYID_FAIL'
