export const GROUP_LIST_REQUEST = 'GROUP_LIST_REQUEST'
export const GROUP_LIST_SUCCESS = 'GROUP_LIST_SUCCESS'
export const GROUP_LIST_FAIL = 'GROUP_LIST_SUCCESS'

export const GROUP_SEARCH_REQUEST = 'GROUP_SEARCH_REQUEST'
export const GROUP_SEARCH_SUCCESS = 'GROUP_SEARCH_SUCCESS'
export const GROUP_SEARCH_FAIL = 'GROUP_SEARCH_FAIL'

export const GROUP_CREATE_REQUEST = 'GROUP_CREATE_REQUEST'
export const GROUP_CREATE_SUCCESS = 'GROUP_CREATE_SUCCESS'
export const GROUP_CREATE_FAIL = 'GROUP_CREATE_FAIL'
export const GROUP_CREATE_RESET = 'GROUP_CREATE_RESET'

export const GROUP_LIST_BYID_REQUEST = 'GROUP_LIST_BYID_REQUEST'
export const GROUP_LIST_BYID_SUCCESS = 'GROUP_LIST_BYID_SUCCESS'
export const GROUP_LIST_BYID_FAIL = 'GROUP_LIST_BYID_FAIL'
