export const ENTERPRISE_LIST_REQUEST = 'ENTERPRISE_LIST_REQUEST'
export const ENTERPRISE_LIST_SUCCESS = 'ENTERPRISE_LIST_SUCCESS'
export const ENTERPRISE_LIST_FAIL = 'ENTERPRISE_LIST_FAIL'

export const ENTERPRISE_SEARCH_REQUEST = 'ENTERPRISE_SEARCH_REQUEST'
export const ENTERPRISE_SEARCH_SUCCESS = 'ENTERPRISE_SEARCH_SUCCESS'
export const ENTERPRISE_SEARCH_FAIL = 'ENTERPRISE_SEARCH_FAIL'

export const ENTERPRISE_CREATE_REQUEST = 'ENTERPRISE_CREATE_REQUSET'
export const ENTERPRISE_CREATE_SUCCESS = 'ENTERPRISE_CREATE_SUCCESS'
export const ENTERPRISE_CREATE_FAIL = 'ENTERPRISE_CREATE_FAIL'
export const ENTERPRISE_CREATE_RESET = 'ENTERPRISE_CREATE_RESET'

export const ENTERPRISE_UPDATE_REQUEST = 'ENTERPRISE_UPDATE_REQUSET'
export const ENTERPRISE_UPDATE_SUCCESS = 'ENTERPRISE_UPDATE_SUCCESS'
export const ENTERPRISE_UPDATE_FAIL = 'ENTERPRISE_UPDATE_FAIL'

export const ENTERPRISE_DELETE_REQUEST = 'ENTERPRISE_DELETE_REQUEST'
export const ENTERPRISE_DELETE_SUCCESS = 'ENTERPRISE_DELETE_SUCCESS'
export const ENTERPRISE_DELETE_FAIL = 'ENTERPRISE_DELETE_FAIL'