export const ENTERPRISE_LIST_REQUEST = 'ENTERPRISE_LIST_REQUEST'
export const ENTERPRISE_LIST_SUCCESS = 'ENTERPRISE_LIST_SUCCESS'
export const ENTERPRISE_LIST_FAIL = 'ENTERPRISE_LIST_FAIL'

export const ENTERPRISE_SEARCH_REQUEST = 'ENTERPRISE_SEARCH_REQUEST'
export const ENTERPRISE_SEARCH_SUCCESS = 'ENTERPRISE_SEARCH_SUCCESS'
export const ENTERPRISE_SEARCH_FAIL = 'ENTERPRISE_SEARCH_FAIL'

export const ENTERPRISE_CREATE_REQUEST = 'ENTERPRISE_CREATE_REQUSET'
export const ENTERPRISE_CREATE_SUCCESS = 'ENTERPRISE_CREATE_SUCCESS'
export const ENTERPRISE_CREATE_FAIL = 'ENTERPRISE_CREATE_FAIL'
export const ENTERPRISE_CREATE_RESET = 'ENTERPRISE_CREATE_RESET'
