export const LESSON_PROGRESS_REQUEST = 'LESSON_PROGRESS_REQUEST'
export const LESSON_PROGRESS_SUCCESS = 'LESSON_PROGRESS_SUCCESS'
export const LESSON_PROGRESS_FAIL = 'LESSON_PROGRESS_FAIL'

export const LESSON_PROGRESS_CREATE_REQUEST = 'LESSON_PROGRESS_CREATE_REQUEST'
export const LESSON_PROGRESS_CREATE_SUCCESS = 'LESSON_PROGRESS_CREATE_SUCCESS'
export const LESSON_PROGRESS_CREATE_FAIL = 'LESSON_PROGRESS_CREATE_FAIL'
export const LESSON_PROGRESS_CREATE_RESET = 'LESSON_PROGRESS_CREATE_RESET'

export const LESSON_PROGRESS_UPDATE_REQUEST = 'LESSON_PROGRESS_UPDATE_REQUEST'
export const LESSON_PROGRESS_UPDATE_SUCCESS = 'LESSON_PROGRESS_UPDATE_SUCCESS'
export const LESSON_PROGRESS_UPDATE_FAIL = 'LESSON_PROGRESS_UPDATE_FAIL'

export const LESSON_PROGRESS_DELETE_REQUEST = 'LESSON_PROGRESS_DELETE_REQUEST'
export const LESSON_PROGRESS_DELETE_SUCCESS = 'LESSON_PROGRESS_DELETE_SUCCESS'
export const LESSON_PROGRESS_DELETE_FAIL = 'LESSON_PROGRESS_DELETE_FAIL'
