export const MEMBER_LIST_REQUEST = 'MEMBER_LIST_REQUEST'
export const MEMBER_LIST_SUCCESS = 'MEMBER_LIST_SUCCESS'
export const MEMBER_LIST_FAIL = 'MEMBER_LIST_FAIL'

export const MEMBER_SEARCH_REQUEST = 'MEMBER_SEARCH_REQUEST'
export const MEMBER_SEARCH_SUCCESS = 'MEMBER_SEARCH_SUCCESS'
export const MEMBER_SEARCH_FAIL = 'MEMBER_SEARCH_FAIL'

export const MEMBER_ACCESS_REQUEST = 'MEMBER_ACCESS_REQUEST'
export const MEMBER_ACCESS_SUCCESS = 'MEMBER_ACCESS_SUCCESS'
export const MEMBER_ACCESS_FAIL = 'MEMBER_ACCESS_FAIL'
