export const LESSSON_PHOTO_LIST_REQUEST = 'LESSSON_PHOTO_LIST_REQUEST'
export const LESSSON_PHOTO_LIST_SUCCESS = 'LESSSON_PHOTO_LIST_SUCCESS'
export const LESSSON_PHOTO_LIST_FAIL = 'LESSSON_PHOTO_LIST_FAIL'

export const LESSSON_PHOTO_CREATE_REQUEST = 'LESSSON_PHOTO_CREATE_REQUEST'
export const LESSSON_PHOTO_CREATE_SUCCESS = 'LESSSON_PHOTO_CREATE_SUCCESS'
export const LESSSON_PHOTO_CREATE_FAIL = 'LESSSON_PHOTO_CREATE_FAIL'
export const LESSSON_PHOTO_CREATE_RESET = 'LESSSON_PHOTO_CREATE_RESET'

export const LESSSON_PHOTO_UPDATE_REQUEST = 'LESSSON_PHOTO_UPDATE_REQUEST'
export const LESSSON_PHOTO_UPDATE_SUCCESS = 'LESSSON_PHOTO_UPDATE_SUCCESS'
export const LESSSON_PHOTO_UPDATE_FAIL = 'LESSSON_PHOTO_UPDATE_FAIL'

export const LESSSON_PHOTO_DELETE_REQUEST = 'LESSSON_PHOTO_DELETE_REQUEST'
export const LESSSON_PHOTO_DELETE_SUCCESS = 'LESSSON_PHOTO_DELETE_SUCCESS'
export const LESSSON_PHOTO_DELETE_FAIL = 'LESSSON_PHOTO_DELETE_FAIL'
