export const RESOURCE_USER_LIST_REQUEST = 'RESOURCE_USER_LIST_REQUEST'
export const RESOURCE_USER_LIST_SUCCESS = 'RESOURCE_USER_LIST_SUCCESS'
export const RESOURCE_USER_LIST_FAIL = 'RESOURCE_USER_LIST_FAIL'

export const RESOURCE_USER_CREATE_REQUEST = 'RESOURCE_USER_CREATE_REQUEST'
export const RESOURCE_USER_CREATE_SUCCESS = 'RESOURCE_USER_CREATE_SUCCESS'
export const RESOURCE_USER_CREATE_FAIL = 'RESOURCE_USER_CREATE_FAIL'
