export const LESSSON_TEXT_LIST_REQUEST = 'LESSSON_TEXT_LIST_REQUEST'
export const LESSSON_TEXT_LIST_SUCCESS = 'LESSSON_TEXT_LIST_SUCCESS'
export const LESSSON_TEXT_LIST_FAIL = 'LESSSON_TEXT_LIST_FAIL'

export const LESSSON_TEXT_CREATE_REQUEST = 'LESSSON_TEXT_CREATE_REQUEST'
export const LESSSON_TEXT_CREATE_SUCCESS = 'LESSSON_TEXT_CREATE_SUCCESS'
export const LESSSON_TEXT_CREATE_FAIL = 'LESSSON_TEXT_CREATE_FAIL'
export const LESSSON_TEXT_CREATE_RESET = 'LESSSON_TEXT_CREATE_RESET'

export const LESSSON_TEXT_UPDATE_REQUEST = 'LESSSON_TEXT_UPDATE_REQUEST'
export const LESSSON_TEXT_UPDATE_SUCCESS = 'LESSSON_TEXT_UPDATE_SUCCESS'
export const LESSSON_TEXT_UPDATE_FAIL = 'LESSSON_TEXT_UPDATE_FAIL'

export const LESSSON_TEXT_DELETE_REQUEST = 'LESSSON_TEXT_DELETE_REQUEST'
export const LESSSON_TEXT_DELETE_SUCCESS = 'LESSSON_TEXT_DELETE_SUCCESS'
export const LESSSON_TEXT_DELETE_FAIL = 'LESSSON_TEXT_DELETE_FAIL'
