name: Docker Builder

on:
  push:

  relase:
  types: [created]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      #- name: Docker login
      #  run: docker login -u ${{ secrets.DOCKERUSERNAME }} -p ${{ secrets.DOCKERAPIKEY }}

      - name: Docker build
        run:  |
        sudo apt update
        sudo apt install npm
        npm install
        npm run build
        export DOCKER_CLI_EXPERIMENTAL=enabled
        source .github/workflows/utils.sh
        repo="earthowned/planetfarms"
        build_image "treehouses/nginx" amd64 "$repo"
        # deploy_image "$repo" amd64
        