name: Manual API Install

on: [push]

jobs:
  api:
    name: Manual API Install
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
          
      - name: Planet Farms API
        run: |
          cd api
          echo "JWT_SECRET=secret" >> .env
          echo "DATABASE_NAME=${{ secrets.POSTGRES_DB }}" >> .env
          echo "DATABASE_USERNAME=${{ secrets.POSTGRES_USER }}" >> .env
          echo "DATABASE_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "DATABASE_HOST=localhost" >> .env
          echo "AUTH_METHOD=local" >> .env
          npm i
          echo "**********************"
          npx sequelize-cli db:migrate &> errorout  
          echo "**********************"
          sed -i '/^==\s/d' errorout
          sed -i '/^$/d' errorout
          echo "**********************"
          [[ -s errorout ]] && echo "not empty" || echo "its empty"
          rm errorout
          touch errorout
          [[ -s errorout ]] && exit 1 || exit 0
