name: Manual Lint Code Base

on:
  workflow_dispatch:
    inputs:

jobs:
  build:
    name: Manual Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Node 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Manual Lint Code Base
        run:  |
          npm install
          npx eslint \"src/**/*.{js,jsx,ts,tsx}\"
   
