name: 'SSH'

on: [push]

jobs:
  ssh-planetforms:
    runs-on: ubuntu-latest
    name: SSH to github.planetfarms.io
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: sshagent
        uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.GPIO_SSHKEY }}
      - name: 
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh root@github.planetfarms.io

